### ISSUE TITLE
Make Windows MSIs more usable

### ISSUE THREAD

**Issue by Prince213** [compnerd/swift-build#179]
MSIs currently have these problems (not in .zip files) :
1. [Shim headers](https://github.com/apple/swift/tree/master/stdlib/public/SwiftShims) are not packed into sdk msi
2. `swiftCore.lib` `swiftrt.obj` `swiftSwiftOnoneSupport.lib` are installed to directory different from the directory in .zip files (`/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift/windows`,  where it should be `/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift/windows/x86_64`)

Sorry, I can't make a PR to fix the problems because I don't know how to do that :( .

**Comment by compnerd** [comment]
Im not sure what you mean by "more usable".  Have you looked at the instructions for using the MSI based usage?  https://github.com/compnerd/swift-build/blob/master/docs/GettingStartedWindows.md

The shim headers are present in the final installation, but you need to install all the MSIs.  I would recommend that you use the installer instead.

**Comment by compnerd** [comment]
The lib files are not in the architecture specific directory because it is possible to have a multi-architecture import library, so I believe that they are in the correct location.  The shim headers are in the correct location.

Going to close this for now as there is no further information on the issue.
