### ISSUE TITLE
Suggestion: Install under C:\Program Files

### ISSUE THREAD

**Issue by wjk** [compnerd/swift-build#187]
It is Windows software convention to install software applications into a subdirectory of `C:\Program Files` (or `C:\Program Files (x86)` for 32-bit programs on 64-bit systems). The WiX installers currently install into `C:\Library\Developer`. I recommend that you update your installers to follow the Windows convention. The Program Files directories have ACLs set on them by Windows that prevent unprivileged users from modifying their contents. By default, the contents of a directory created in the root of C: is writable by all users.

I would recommend installing into `C:\Program Files\Swift` instead of `C:\Library\Developer`. Unless it would cause problems (as you know more about making Swift run on Windows than I do) I would also recommend that you trim some of the subdirectories off of the path to the directories containing actual files. I don't have a firm idea of what the resulting directory structure would look like yet, however. IMHO parroting Xcode’s directory structure when running on Windows makes little sense. Thanks!

**Comment by compnerd** [comment]
The "Xcode" directory structure is actually kind of interesting in some senses.

`/Library` - holds pretty much all the content - but no worse than `C:\Program Files`
`/Developer` - possibly superfluous, but differentiates the runtime and developer components
`/Toolchains` - this holds the actual toolchains (you may have more than one installed in parallel)
`/Platforms` - this holds the actual SDKs (you may have more than one installed in parallel

`/Library/Developer/Toolchains/..../usr/bin/` is actually something which makes it slightly easier to deal with inside of the implementation since there are assumptions about the directory structure.

`/Library/Developer/Platforms/[Windows|Linux|Android].platform/Developer/SDKs/...` have the SDK content.  Especially with some planned work to remove the need for some of the extra flags and have `-sdk` take a single location, this makes it somewhat obvious and is why I've been trying to keep that structure.

In reality, this wasn't actually just parroting the Xcode structure, I have given it quite a bit of consideration.

I can see where you are coming from.  I would be open to the idea of having an option (preferably marked as advanced) that would let you get an alternative layout which could reside in `%ProgramFiles%`.

**Comment by wjk** [comment]
The directory structure we have does have one major problem. As I discovered in #194, the separation of the Swift compiler into `C:\Library\Toolchains` and the Swift libraries into `C:\Library\Developer\Platforms` makes the Swift compiler choke by default. I must pass the full path to the Windows.sdk directory into every swiftc command line I run for it to work.

I would suggest moving the contents of `…\Windows.platform\Developer\SDKs\Windows.sdk\usr` into `…\Toolchains\*.xctoolchain\usr`. The Swift compiler should pick them up automatically then. I can prepare a PR if that helps. Thanks!

**Comment by wjk** [comment]
Alternatively, do you know how to make swiftc accept a name for the `-sdk` parameter instead of an unwieldy full path?

**Comment by compnerd** [comment]
Taking a name won't work per se, because it doesn't know where to look.  I do not wish to add the SDKs into the toolchain directory because I want to have the ability to have multiple Windows SDKs available at once as well as to support multiple architectures.

That does mean that it will need the user to specify the path to the SDK.  I think that changing the driver to give it a default search path for the SDK makes sense, or perhaps having it honor `SDKROOT`.

Can you explain what you mean by the need for the flags preventing CMake from compiling Swift?

**Comment by wjk** [comment]
If I run CMake on a Swift project, CMake will attempt to compile a "Hello, World"-style program to ensure that the Swift compiler works. Since without the `-sdk` flag (which AFAIK cannot be specified at this point in time) the compiler issues the error described in #194. CMake then panics, and refuses to continue configuring the project.

**Comment by compnerd** [comment]
That can be specified using `-DCMAKE_Swift_FLAGS=`.  Something like `-DCMAKE_Swift_FLAGS="-sdk C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk ...` is needed.  See the getting started docs or the CI configuration - both of them do this.

**Comment by compnerd** [comment]
Coming back to this, trying to figure out what needs to be done.  I think that there are two separate issues being discussed here:

1. the experience on Windows is rubbish due to the need for the current set of flags which amount to:
```
-sdk %SystemDrive%\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk
-I %SystemDrive%\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\windows
-L %SystemDrive%\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\windows\x86_64
```
I believe that it should be possible to improve this to:

```
-sdk %SystemDrive%\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk
```

However, that is not in the build system but in the compiler.

2. The install location is not traditionally Windows.

Moving the locations is certainly possible, but I would like to retain the default to be `%SystemDrive%`, and have an option to install to `%ProgramFiles%` (as this is 64-bit build, it belongs in `%ProgramFiles%` and not `%ProgramFiles(x86)%`).  Adding an advanced option to change the location is acceptable with the caveat that it does complicate the usage - the space in the path means that quoting must be done properly.

I think that the only thing that makes sense for this repository is the second issue (to which the issue description is relevant).

I'd like to get your opinion on the second one @wjk

**Comment by compnerd** [comment]
Some better documentation on the layout at https://github.com/compnerd/swift-build/blob/master/docs/Layout.md.  @wjk perhaps you can go over it if you have some time?  I think that it can be useful to ensure that the document clearly conveys the motivations for the layout.

**Comment by wjk** [comment]
Sounds good to me, as long as we don't have C:\usr\bin or anything like that. Also note that WiX can set permissions on the directories it installs. With a bit of research, we can set the ACL on `C:\Developer` to be identical to that of `C:\Program Files`, and then I’d have no complaints. Thanks!

**Comment by compnerd** [comment]
Definitely not looking for `C:\usr\bin`.  I think that we could move the runtime into `%ProgramFiles%` though!  That way we dont have to have `/Library/ICU-64` and can have `%ProgramFiles%\ICU-64` for example.

**Comment by compnerd** [comment]
We did this for a while, but we now install into a per-user installation instead.
