### ISSUE TITLE
Cannot use Foundation

### ISSUE THREAD

**Issue by AriX** [compnerd/swift-build#212]
Thanks for the great project!

Unfortunately, using the current release package (from "install.exe"), I can't use Foundation. If my swift file includes Foundation, the compiler prints:

`missing required module 'CoreFoundation'`

So far I can't figure out why this is happening, or how to work around it. Is Foundation expected to work in this release?

**Comment by compnerd** [comment]
Yes, Foundation [should] work[s].  I suspect that the issue is in your compiler invocation.  Did you follow the instructions in the [Getting Started (Native)](https://github.com/compnerd/swift-build/blob/master/docs/GettingStartedWindows.md) guide?  In particular, ensure that you are passing in the flags that it is indicating that you should be passing.

Can you share the project that you are building?

**Comment by AriX** [comment]
Wow - you're right. Sorry for my poor instruction reading. Adding Foundation to the HelloMinimal code sample works fine, and adding the flags "-sdk %SDKROOT% -I %SDKROOT%/usr/lib/swift -L %SDKROOT%/usr/lib/swift/windows" when invoking `swiftc` solves my problem in general. I thought I had tried that already, but alas, it appears not.

**Comment by compnerd** [comment]
If there is a way to make that clearer/more obvious, please let me know.  People often get stumped about the need for the flags :-(

**Comment by AriX** [comment]
Just one idea, it could be nice to include an example of how to use the compiler directly (i.e. `swiftc`) without using cmake. I'm not familiar with cmake so that tripped me up.

Also: which shell do you use when doing this type of development? Are you just using regular Command Prompt? I'm very unfamiliar with Windows and found interacting with the Command Prompt to be a challenge. I got a little further by installing Git Bash.
