### ISSUE TITLE
MinGW support for Windows

### ISSUE THREAD

**Issue by nu8** [compnerd/swift-build#239]
currently for Windows, Swift is looking for header provided by MSVC. However
other options are available for this, namely MinGW. Here are some distributions:

- <https://github.com/mstorsjo/llvm-mingw>
- <https://packages.msys2.org/base/mingw-w64-gcc>

These are at least an order of magnitude smaller than Visual Studio, even
considering a minimal Visual Studio install. It would be helpful to some users
to have this option.

**Comment by compnerd** [comment]
The MinGW distribution would be the same size - the headers and import libraries would add up to the same results.  Using MinGW also prevents using the other parts of MSVC for integration with the rest of the system.  I think that this results in a much nicer system and there is no real size penalty here (in fact, it is smaller because MinGW does not need to be distributed with the application itself).

**Comment by nu8** [comment]
Swift requires a C compiler and a C standard library (`stdio.h` and similar).
I am not suggesting that this be included with the Swift distribution.

I am suggesting that Swift could allow C environments for Windows other than
Visual Studio. An install for Visual Studio is about 20 GB, even just the build
tools:

<https://nu8.github.io/rosso/windows-tools>

Compared to other options, which are under 200 MB:

<https://github.com/mstorsjo/llvm-mingw/releases>

So I am not sure where you are getting information about them being the same
size.

**Comment by MaxDesiatov** [comment]
Even though I haven't tried using MINGW, I strongly support all efforts in making Swift distribution and its dependencies smaller, at least as an option. Bandwidth and disk space are limited resources, making Swift lightweight will make it much more compelling, especially in an educational setting.

**Comment by MikeCodesDotNET** [comment]
@nu8 Visual Studio is a lot smaller than 20gb. The core editor is about 600mb alone, and then optional build tools add to that. 

I’ve a rather exhaustive selection of VS components installed and I’m using 14gb. I could slim this down massively if I were only working on one project.

**Comment by compnerd** [comment]
@MaxDesiatov i think that there’s some miscommunication or misunderstanding here.

Visual Studio is not a dependency for distribution.  It is a developer requirement.  It is not the full visual studio that is required but specifically the windows SDK, ucrt, MSVCRT, and ATL bits that are required.  The ATL development headers are for LLDB, the ucrt/msvcrt headers are the C library, and the windows SDK headers are the SDK headers.  None of this content is distribution content.

The other dependencies from visual studio are git, cmake, and python, which are required to build.  These are not special and not required for distribution of applications, but is required for development environments.

The MSVC toolchain is required to at least bootstrap.  This is not a distribution dependency and cannot in fact be distributed as per my understanding.

The runtime dependencies is msvcrt only which is relatively small and only needed if you want to not require that’s the user download msvcrt themselves from Microsoft.  The other dependency is ICU which is a requirement from the standard library.

**Comment by MaxDesiatov** [comment]
>Visual Studio is not a dependency for distribution. It is a developer requirement.
Do you mean it's a developer requirement for developers who're working on the Swift toolchain? Or developers who'd use Swift to build their own apps with Swift?

My point was that a beginner developer who would like to get their feet wet with using Swift shouldn't need to download multiple gigabytes of dependencies just to try it. This is not applicable only to Windows, but I was thinking that with how modular the Windows distribution is, many of these dependencies would be optional even for developers using Swift to build their own apps. For example, the distribution of Rust is about ~150 megabytes on Windows. As far as I understand, that download is enough to get started. I don't have a Windows installation around to try, but I hope that Swift installation would be (or currently is already?) of comparable size with all the dependencies.

**Comment by nu8** [comment]
@MaxDesiatov yes thats exactly my point.

With language like Rust, or even Go, you have a single download of about 200 MB,
then you are ready to get started. Thats because both languages offer both
MSVC and GNU toolchains. With the MSVC toolchain, Visual Studio is required.
With the GNU toolchain, MinGW is used.

With any language that offers only MSVC option (like Swift), users are required
to install the 10 GB Visual Studio to be able to create any programs.

**Comment by compnerd** [comment]
@nu8 I think that’s the disconnect.  You don’t need visual studio in its entirety to build programs with swift.  You need the windows SDK and msvcrt library (and the swift dependencies).  That’s the headers and import libraries.  These sum up to ~300M which is roughly in the same ballpark.

**Comment by nu8** [comment]
@compnerd please show me where this 300M download is. If you can provide the link, I would be happy, because my tests have all shown number over 10 GB:

https://nu8.github.io/rosso/windows-tools

**Comment by compnerd** [comment]
You are downloading the full offline installer, you should use the online installer with specific components:

- Microsoft.VisualStudio.Component.Windows10SDK.18362
- Microsoft.VisualStudio.Component.Windows10SDK

I believe that should have all the dependencies that are required.  There is the standalone SDK as well which I don't have a link to but it is available somewhere through MSDN.

**Comment by nu8** [comment]
Again, Im not sure where youre getting these numbers. Even if you only consider
the `Microsoft.VisualStudio.Component.VC.Tools.x86.x64` package, which is
required for `nmake.exe` and similar, that package alone is 648 MB:

<https://github.com/microsoft/msbuild/issues/5197>

This package is required, by your own admission:

<https://github.com/compnerd/swift-build/blob/master/docs/GettingStartedWindows.md>

That doesnt even touch either of the packages you speak of. So I think you
should revisit your thinking about the size requirements.

**Comment by compnerd** [comment]
`nmake` is not required, nor are any of the tools in `Microsoft.VisualStudio.Component.VC.Tools.x86.x64`.  If you do not install that, just pass along `-use-ld=lld` and you will be fine :).

**Comment by nu8** [comment]
Your own documentation, that I previously linked, contradicts what you just said. So I will defer to that until its changed.

If you want to argue with yourself, thats your business. But I wont continue if you cant get your own story straight.

**Comment by nu8** [comment]
> `nmake` is not required, nor are any of the tools in
> `Microsoft.VisualStudio.Component.VC.Tools.x86.x64`.

Your own documentation, that I previously linked, contradicts what you just
said. So I will defer to that until its changed. If you want to argue with
yourself, thats your business. But I wont continue if you cant get your own
story straight.

> If you do not install that, just pass along `-use-ld=lld` and you will be
> fine :).

`lld.exe` doesnt exist on any stock Windows system, so im not sure what youre
suggesting here. Installing Swift, and Visual Studio, and LLVM? Also for fun,
I went ahead and downloaded the other two options you listed, since you refuse
to see the size for what is really is. Here you go:

~~~
Microsoft.VisualStudio.Component.Windows10SDK.18362
936 MB

Microsoft.VisualStudio.Component.Windows10SDK
226 MB
~~~

**Comment by compnerd** [comment]
Right, `lld.exe` is not part of the host system, but it is part of the Swift toolchain, so that shouldn't be an issue.  In order to develop with Swift, you would need to install the Swift toolchain and Visual Studio.  LLVM is already distributed as part of the toolchain (that includes the tools that you need for development).  That includes the compiler, linker, and assembler.

The Windows10SDK is the SDK, there is no smaller version that would be sufficient.  That is the equivalent of the Apple SDK (which is part of Xcode, here its a part of Visual Studio or the Build Tools) and the development headers on Linux.  It provides the headers (e.g. `AdvAPI.h` for registry access) and the import libraries for linking.  These cannot be legally redistributed, so the user needs to install the SDK themselves.

**Comment by nu8** [comment]
Nothing youve just said addresses the following fact. In the official
documentation, its noted that `Microsoft.VisualStudio.Component.VC.Tools.x86.x64`
is a "Required Visual Studio Component":

<https://github.com/compnerd/swift-build/blob/master/docs/GettingStartedWindows.md>

Then once challenged on the size, you come back and say:

> `nmake` is not required, nor are any of the tools in
> `Microsoft.VisualStudio.Component.VC.Tools.x86.x64`

<https://github.com/compnerd/swift-build/issues/239#issuecomment-634989184>

Then you claim without evidence of some easily disproven size:

> You need the windows SDK and msvcrt library (and the swift dependencies).
> That’s the headers and import libraries. These sum up to ~300M which is
> roughly in the same ballpark.

<https://github.com/compnerd/swift-build/issues/239#issuecomment-634930450>

To which I personally tested and found demonstrably false:

~~~
936 MB Microsoft.VisualStudio.Component.Windows10SDK.18362
648 MB Microsoft.VisualStudio.Component.VC.Tools.x86.x64
226 MB Microsoft.VisualStudio.Component.Windows10SDK
~~~

Even under the most genererous interpretation, when we disregard the official
documentation Ive linked in this comment, your estimate of 300 MB is off by
at least a factor of 3. So I will ask, why are you misrepresenting the
current landscape of Visual Studio distribution? Did you just not realize
how large it actually was?

**Comment by compnerd** [comment]
Yes, the documentation states the VC tools, because the default linker is `link.exe`.  However, that is not trying to minimize the developer environment size.  It is trying to make the defaults work out of the box.  The toolchains that I am building _should_ be complete.  If there are missing pieces that require tools outside of it, I would like to know that.  In fact, it was pointed out to me that `clangd` is missing and would be useful and I did add that to the image.

I don't recall the SDK being that large; when I copied it last time, it was ~300M.  I'm not trying to misrepresent the landscape, I'm going by the numbers that I had based on the SDK that I had (it was a snapshot of a previous SDK that I was using to cross-compile from Linux to Windows).

Checking now on Windows:
Include\10.0.18362.0 - ~312M
Lib\ucrt\x64, Lib\um\x64 - ~200M

Okay, so this is ~500M, a bit higher than I remember, but okay things have changed.  I compressed this locally, the compressed archive is 37,243,122 bytes (~35M).

I'm not trying to misrepresent the information, nor contradict what I've documented (although, I admit that my documentation could use a lot more attention).  I'm trying to provide you with ways to avoid some of the dependencies with the understanding that you would like to reduce the download size at all costs.  That means that you will have to adjust how things are built etc. but perhaps it will help you achieve what you are trying to do.

**Comment by nu8** [comment]
Detail matter. Some new user, who is using Windows and considering using Swift
for the first time, isnt going to be using some old Visual Studio that you have
on your computer. They are going to download it now. And based of the current
instruction linked here:

<https://github.com/compnerd/swift-build/blob/master/docs/GettingStartedWindows.md>

they are going to be downloading 1,810 MB worth of Microsoft programs, which
**doesnt even include Swift itself**.

So for you to come and say 300 MB, you can understand how a person could see
that as misleading. Since youre in a position to be interacting with first time
Swift Windows users, it would be helpful to put yourself in their shoes, rather
than looking from your own point of view.

You cant assume the end user has anything, so the average experience is going to
be based on the direction you give. And the current direction is over 2 GB after
all is said and done, not 300 MB.

**Comment by compnerd** [comment]
I think I know the difference for the numbers that I remember!  If I check after removing the `winnt` and `cppwinrt` directories (which are not needed), the SDK comes in at 395,240,988 bytes (~375 M).  The compressed archive is 28,856,375 bytes (~27M).

That said, I cannot legally redistribute that AFAIK, so I have to direct them to Microsoft to acquire the SDK.  If you have a way to get the SDK legally such that it is the trimmed version, I'm happy to have documentation for that.

**Comment by nu8** [comment]
If you take Rust for example:

<https://forge.rust-lang.org/infra/other-installation-methods#standalone>

They distribute these:

- <https://static.rust-lang.org/dist/rust-1.43.1-x86_64-pc-windows-gnu.msi>
- <https://static.rust-lang.org/dist/rust-1.43.1-x86_64-pc-windows-msvc.msi>

The GNU version, includes MinGW build tools. The MSVC version, relies on the
user install Visual Studio build tools. Other languages like Go dont rely on
MSVC at all. The only other language I know of any significance, that uses
Visual Studio only, is Pony:

<https://github.com/ponylang/ponyc/issues/2079>

**Comment by compnerd** [comment]
AIUI, Go and Rust also do not rely on the system at all - they do not bridge into the system's libraries at the same level.  They are fundamentally designed differently.

The Swift runtime requires the System's C library and potentially others (e.g. ICU).  This requires additional dependencies that Go and Rust do not have to deal with.  That is a fundamental difference.  That doesn't mean that nothing can be done, but, that is _way_ out of the goals of getting regular builds and setting up infrastructure to make it easier to build the toolchain.

Because I've not played with it so I really do not know how Rust and Windows work together, how does Rust bridge to the Windows Runtime when you include a crate?  Does that require the Windows SDK?  If not, what do they do to avoid that dependency?

**Comment by nu8** [comment]
Youre talking about Build time versus Runtime time dependencies. With Go, after
you compile the executable still relies on these existing:

~~~
C:\Windows\system32\kernel32.dll
C:\Windows\system32\ntdll.dll
~~~

same with Rust:

~~~
C:\Windows\system32\ADVAPI32.dll
C:\Windows\system32\KERNEL32.dll
C:\Windows\system32\RPCRT4.dll
C:\Windows\system32\WS2_32.dll
C:\Windows\system32\msvcrt.dll
C:\Windows\system32\ntdll.dll
~~~

but thats not an issue as those libraries are preinstalled with every Windows
version since at least Windows 7. The difference between these languages and
Swift is the *build time dependencies*. Go, and GNU Rust, bundle the build time
dependencies, such as Compiler Linker and Standard library, so that the user is
not required to go get them.

Not only does Swift not do that, but Swift doesnt even allow the user to choose
what build tools they use, forcing them to install the nearly 2 GB worth of
Microsoft build tools previously discussed. So if Swift was able to have a
bundle with included MinGW build tools, or even just have that as an option
where the user could download MinGW, it would be better.

**Comment by compnerd** [comment]
There is a difference between runtime and build time dependencies.  The runtime dependencies on the system should be the same, but there are additional runtime dependencies because again, Swift requires more from the system.

This discussion was about build time dependencies.  The Swift toolchain can be built with the full toolchain, and the builds that I have configured are complete in that sense.  The dependencies are not on the tools, but the headers and the import libraries (`*.h`, `*.lib`), these are not tools.  If Go and Rust are bundling the SDK, Id love to get more information on how they are dealing with the licensing issues, because my understanding (which may be incorrect, IANAL), is that you cannot redistribute the headers and the import libraries from the SDK.  They are needed for building against the SDK.

I can see how Rust could avoid the header dependencies - force the user to transliterate the declarations as they cannot interoperate with C in the same way that Swift can.  That is, IMO, a feature here - you don't need to transliterate the headers, you just use the headers as Microsoft provides.

The build tools even from MinGW should not be needed either.  The compiler - `swiftc`, linker - `lld`, and standard library - `swiftCore`, are already available.  Now, `lld` is not the default, so, if you do not want to install the VS tools for a single executable, which is understandable, pass `-use-ld=lld`.  In fact, the core libraries are built using `lld` rather than `link`.  But, this is not the basic use case, so I expect that users doing that are aware of what they are doing.  If you want to document the fact that `lld` is available as part of the toolchain, sure, Im happy to accept a PR to add that to the documentation.

Can you list what build tools you believe to be required to use the swift toolchain?

**Comment by nu8** [comment]
> If Go and Rust are bundling the SDK, Id love to get more information on how
> they are dealing with the licensing issues, because my understanding (which
> may be incorrect, IANAL), is that you cannot redistribute the headers and the
> import libraries from the SDK.

In 2008, a "clean room" implementation of the Windows API was completed. This
effort became known as the MinGW-W64 project:

<https://sourceforge.net/p/mingw-w64/wiki2/History>

because of this effort, MinGW-W64 can be distributed alongside other tools
without being encumbered by Microsoft SDK restrictions. This has allowed
releases like Rust with included Windows build tools, libraries and headers:

<https://static.rust-lang.org/dist/rust-1.43.1-x86_64-pc-windows-gnu.msi>

or LLVM build tools, with Windows libraries and headers:

<https://github.com/mstorsjo/llvm-mingw>

or even each piece separate, build tools, libraries and headers:

<https://packages.msys2.org/group/mingw-w64-x86_64-toolchain>

Again this is not some new development. These items has been available for at
least a decade. It might be helpful to you to research this some more, so you
know what options are available. You arent locked in to requiring the Windows
SDK.

> Can you list what build tools you believe to be required to use the swift
> toolchain?

This isnt about me. But as far as the issues Ive personally had, is that Swift
doesnt bundle the Windows headers:

<https://github.com/compnerd/swift-build/issues/225>

and the maintainer (you) is under the false assumption that no version or
implementation of these headers are available in a license unrestricted fashion.

**Comment by compnerd** [comment]
I’m aware of MinGW, however, AFAIK it is not the same thing as the Microsoft headers.  MinGW is  never ready to go on day 0 of a Microsoft release.  It also does not use the Microsoft ABI, which means that it is not viable for compatibility.  I assume that you are aware that they are not drop in replaceable, which means that they are not an alternative to the windows SDK.  MinGW support is completely different from windows support (this is why there are two different targets for windows vs MinGW).

**Comment by compnerd** [comment]
It just occurred to me that there may be some misunderstanding between what I've been trying to convey.

The Windows port is the Windows port.  MinGW is not Windows.  I think that it is important that we do not conflate Windows and MinGW.  They are unrelated targets, and are fundamentally different.

There was at one point a MinGW port of Swift.  If you are interested in reviving that, then great!  Because the port was there at one point, which will ease some of the work, it is still a fun challenge.  If you interested in taking on that challenge, then the proper place for that work is the Swift repository.

This project is not affiliated with the Swift project, it is something that I created to share the infrastructure that I have worked on for quite some time to ease some of the challenges with getting started with building Swift on and for Windows.  If you find that this work is beneficial for what you are doing, then please borrow whatever it is that you find beneficial, I have tried to place it under a reasonably permissive license.

Now, if you have documentation/suggestions on how to improve the Windows port then of course I am interested in hearing about that.

**Comment by wayne-zhang** [comment]
Current Windows port is pretty much useless from a Swift developers point of view, it (Swift 5.3 for Windows 10) doesn't work out of box even though when Windows 10 SDK has been installed. It is a big step to Windows Swift, but there is a far way to go to the same level of other platforms such as Linux (installed developer essentials + Swift everything works).
