### ISSUE TITLE
Extract CoreFoundation.lib from the build?

### ISSUE THREAD

**Issue by tomleavy** [compnerd/swift-build#366]
Hello,

I have a project that I would like to just use CoreFoundation as a library (in C) as its own module. I noticed that although the CoreFoundation headers are part of the installer, the .lib file is not. It's a pain to build for Windows, so I was hoping I could utilize this project to get that library.

**Comment by compnerd** [comment]
That is intentional - CoreFoundation is not supported, and not supposed to be accessible.  That includes the headers.  Could you point out where in the install it accidentally leaked the headers?

If you wish to take responsibility for it and use it, you could build it separately outside of the swift project, which may cause more problems than it solves if you intend to use it in a swift project.

**Comment by tomleavy** [comment]
Makes sense, I see the headers in the Swift 5.3 install but not in the Swift 5.4 one on Swift.org, so looks like you took care of it already. They were in the windows.sdk under lib. We have some C code we would like to share between macOS and Linux that uses CF (and not swift). I'll probably be re-writing to remove CF on Linux instead

**Comment by compnerd** [comment]
Good luck.  CF is definitely convenient to have handy, but since upstream has declared that CF is an internal detail of Foundation, and use of it on non-Darwin platforms is unsupported.  On Linux, because they had accidentally exposed it, they haven't removed it yet, but recommend against the introduction of new dependencies.
