### ISSUE TITLE
Swift release on Windows blocked by Windows Defender

### ISSUE THREAD

**Issue by vricosti** [compnerd/swift-build#518]
Hello,

I wanted to test swift on Windows (swift-5.8-RELEASE-windows10.exe) but when I try to install it it get blocked by Windows Defender.
So can we trust your installer :-) ?
Wouldn't be possible to sign with an officiel certificate to avoid this ?

**Comment by compnerd** [comment]
What do you mean by official certificate?  If you mean a non-self-signed one, that is something which requires a purchased certificate which no one has volunteered to cover the costs for.  As such there is no way to get the certificate cross signed by a trusted root authority.

**Comment by vricosti** [comment]
> What do you mean by official certificate? If you mean a non-self-signed one, that is something which requires a purchased certificate which no one has volunteered to cover the costs for. As such there is no way to get the certificate cross signed by a trusted root authority.

Yes I mean a purchased certificate, how much does it cost ?

**Comment by compnerd** [comment]
I don't think that the submitting the binary to Microsoft works, as we churn through them pretty rapidly (these are nightly snapshots after all).  The EV certificate is the solution, but that is not exactly cheap, so that is currently not viable ATM.  It is unfortunate that it will prevent you from using it.  The alternative is that you can down the binaries directly from Azure if you like (the signature is the same) - but you know that the binaries that are being packaged are the ones built there.
